export const safeUserSelect = {
  id: true,
  role: true,
  firstName: true,
  middleName: true,
  lastName: true,
  email: true,
  mobile: true,
  profileImage: true,
  employeeId: true,
  managerId: true,
  organizationId: true,
  organization: {
    select: {
      name: true,
      slug: true,
      prefix: true,
      status: true,
      address: true,
      gstin: true,
      mobile: true,
      email: true,
      companyLogo: true,
      qrCode: true,
      signature: true,
    },
  },
  joiningDate: true,
  designation: true,
  status: true,
  lastLoginAt: true,
  passwordChangedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;
