import { Check, X } from "lucide-react";
import { Card } from "@/components/ui/card";
import StatusBadge from "@/components/common/StatusBadge";
import LoadingState from "@/components/common/LoadingState";
import ErrorState from "@/components/common/ErrorState";
import EmptyState from "@/components/common/EmptyState";
import { useAppSelector } from "@/hooks/useRedux";
import { ROLES } from "@/constants/roles";
import {
  isNoSubscriptionError,
  useSubscription,
  useUsage,
} from "../../hooks/useBilling";
import {
  PLAN_INTERVAL_LABELS,
  SUBSCRIPTION_STATUS_BADGE_TYPE,
  SUBSCRIPTION_STATUS_LABELS,
  formatDate,
  formatLimit,
  formatPrice,
} from "../../constants/labels";
import UsageMeter from "../usage/UsageMeter";

/**
 * Tenant-facing billing screen.
 *
 * Read-only by design: while billing is operated manually, changing a plan is a
 * conversation, not a button. The super-admin console is where plans are
 * actually assigned.
 */
const BillingView = () => {
  const user = useAppSelector((s) => s.auth.user);
  const isSuperAdmin = user?.role === ROLES.SUPER_ADMIN;

  const { data, isLoading, isError, error, refetch } = useSubscription();
  const { data: usageData, isLoading: usageLoading } = useUsage();

  const subscription = data?.data;
  const usage = usageData?.data;

  // A super-admin has no organization of their own; the queries stay disabled
  // until they scope into a tenant workspace.
  if (isSuperAdmin && !subscription && !isLoading) {
    return (
      <EmptyState
        title="No organization selected"
        description="Open an organization's workspace to see its billing, or use the subscriptions console to manage plans across all tenants."
      />
    );
  }

  if (isLoading) return <LoadingState message="Loading billing..." />;

  // No plan assigned is a distinct, actionable state — not a load failure. Say
  // what is wrong and who fixes it, and do not offer a retry that cannot help.
  if (isError && isNoSubscriptionError(error)) {
    return (
      <EmptyState
        title="No plan assigned"
        description="This organization does not have a subscription yet. Contact your platform administrator to have a plan assigned."
      />
    );
  }

  if (isError || !subscription) {
    return (
      <ErrorState
        message="Could not load your subscription."
        onRetry={() => void refetch()}
      />
    );
  }

  const { plan } = subscription;
  const isFree = plan.priceMinor === 0;
  const seatFeature = subscription.features.find((f) => f.key === "MAX_USERS");
  const toggles = subscription.features.filter((f) => f.kind === "toggle");

  return (
    <div className="space-y-6">
      {/* ------------------------------ Plan ------------------------------ */}
      <Card className="p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="min-w-0">
            <p className="text-sm text-muted-foreground">Current plan</p>
            <h2 className="mt-1 text-2xl font-bold text-foreground">
              {plan.name}
            </h2>
            {plan.description && (
              <p className="mt-1 text-sm text-muted-foreground">
                {plan.description}
              </p>
            )}
          </div>

          <div className="text-right">
            <StatusBadge
              status={subscription.effectiveStatus}
              label={SUBSCRIPTION_STATUS_LABELS[subscription.effectiveStatus]}
              type={SUBSCRIPTION_STATUS_BADGE_TYPE[subscription.effectiveStatus]}
            />
            <p className="mt-2 text-2xl font-bold text-foreground">
              {isFree ? "—" : formatPrice(plan.priceMinor, plan.currency)}
            </p>
            {!isFree && (
              <p className="text-xs text-muted-foreground">
                per {PLAN_INTERVAL_LABELS[plan.billingCycle]}
              </p>
            )}
          </div>
        </div>

        {/*
          `reason` is generated by resolveSubscriptionState on the server, so the
          wording here always matches what the enforcement layer actually did.
        */}
        {subscription.reason && (
          <p className="mt-4 rounded-lg bg-muted/50 p-3 text-sm text-foreground">
            {subscription.reason}
          </p>
        )}

        <dl className="mt-6 grid gap-4 border-t border-border pt-4 sm:grid-cols-3">
          <div>
            <dt className="text-xs text-muted-foreground">Seats included</dt>
            <dd className="mt-0.5 text-sm font-semibold text-foreground">
              {formatLimit(seatFeature?.valueInt ?? null)}
              {seatFeature?.origin === "override" && (
                <span className="ml-1 text-xs font-normal text-muted-foreground">
                  (custom)
                </span>
              )}
            </dd>
          </div>
          <div>
            <dt className="text-xs text-muted-foreground">
              {subscription.effectiveStatus === "TRIALING"
                ? "Trial ends"
                : "Renews on"}
            </dt>
            <dd className="mt-0.5 text-sm font-semibold text-foreground">
              {subscription.effectiveStatus === "TRIALING"
                ? formatDate(subscription.trialEndsAt)
                : formatDate(subscription.currentPeriodEnd)}
            </dd>
          </div>
          <div>
            <dt className="text-xs text-muted-foreground">Billing contact</dt>
            <dd className="mt-0.5 truncate text-sm font-semibold text-foreground">
              {subscription.billingEmail ?? "—"}
            </dd>
          </div>
        </dl>
      </Card>

      {/* ----------------------------- Usage ------------------------------ */}
      <Card className="p-6">
        <h3 className="text-lg font-bold text-foreground">Usage</h3>
        <p className="mt-1 text-sm text-muted-foreground">
          Seats are enforced. Other figures are shown for information.
        </p>

        {usageLoading || !usage ? (
          <div className="mt-6">
            <LoadingState message="Loading usage..." />
          </div>
        ) : (
          <div className="mt-6 space-y-6">
            {usage.metrics.map((metric) => (
              <UsageMeter
                key={metric.key}
                metric={metric}
                description={
                  metric.key === "MAX_USERS"
                    ? "Disabled users do not use a seat."
                    : undefined
                }
              />
            ))}
          </div>
        )}
      </Card>

      {/* ---------------------------- Features ---------------------------- */}
      <Card className="p-6">
        <h3 className="text-lg font-bold text-foreground">What's included</h3>
        <ul className="mt-4 space-y-2">
          {toggles.map((feature) => (
            <li key={feature.key} className="flex items-start gap-2 text-sm">
              {feature.valueBool ? (
                <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-600 dark:text-green-400" />
              ) : (
                <X className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground/50" />
              )}
              <span
                className={
                  feature.valueBool
                    ? "text-foreground"
                    : "text-muted-foreground line-through"
                }
              >
                {feature.label}
              </span>
            </li>
          ))}
        </ul>
      </Card>

      <p className="text-sm text-muted-foreground">
        To change your plan or update billing details, contact your account
        manager.
      </p>
    </div>
  );
};

export default BillingView;
