import { useLocation, useNavigate, useParams } from "react-router-dom";
import EmptyState from "@/components/common/EmptyState";
import LoadingState from "@/components/common/LoadingState";
import { useProspectDetail } from "../../hooks/useProspects";
import ProspectFormContainer from "../forms/ProspectFormContainer";
import { withSuperAdminOrganizationScope } from "@/utils/orgRoutes";

const ProspectDetail = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { id } = useParams();
  const scopedPath = (path: string) =>
    withSuperAdminOrganizationScope(path, location.pathname);
  const isCreate = !id || id === "new";

  const {
    data: prospect,
    isLoading,
    error,
  } = useProspectDetail(isCreate ? undefined : id);

  if (isCreate) {
    return (
      <EmptyState
        title="Create Prospects From Qualified Leads"
        description="Prospects in this phase are generated by converting a qualified lead, not by creating them directly from the prospects screen."
      />
    );
  }

  if (isLoading) {
    return <LoadingState message="Loading prospect workspace..." />;
  }

  if (error) {
    return (
      <EmptyState
        title="Error loading prospect"
        description="There was an error fetching the prospect details. Please try again later."
      />
    );
  }

  if (!prospect) {
    return (
      <EmptyState
        title="Prospect not found"
        description="The prospect you are trying to view does not exist."
      />
    );
  }

  return (
    <ProspectFormContainer
      prospect={prospect}
      onBack={() => navigate(scopedPath("/prospects"))}
    />
  );
};

export default ProspectDetail;
