/**
 * Error Codes for Client-Side Handling
 */
export const ERROR_CODES = {
  // Authentication Errors
  AUTH_INVALID: "AUTH_INVALID",
  AUTH_EXPIRED: "AUTH_EXPIRED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_USER_DISABLED: "AUTH_USER_DISABLED",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",

  // Authorization Errors (2xxx)
  // Organization Errors
  ORG_REQUIRED: "ORG_REQUIRED",
  ORG_FORBIDDEN: "ORG_FORBIDDEN",
  ORG_SUSPENDED: "ORG_SUSPENDED",
  
  // Billing
  /** Subscription lapsed — the client should route the user to billing. */
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  SEAT_LIMIT_REACHED: "SEAT_LIMIT_REACHED",
  /** A plan limit (leads, prospects, quotations, items) is exhausted. */
  LIMIT_REACHED: "LIMIT_REACHED",
  /** The plan does not include this feature (toggle is off). */
  FEATURE_NOT_AVAILABLE: "FEATURE_NOT_AVAILABLE",

  // Rate Limit
  RATE_LIMIT: "RATE_LIMIT",

  // Validation Errors (3xxx)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  VALIDATION_FIELD_REQUIRED: "VALIDATION_FIELD_REQUIRED",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",

  // Resource Errors (4xxx)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",

  // Database Errors (5xxx)
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",

  // Business Logic Errors (6xxx)
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  INVALID_OPERATION: "INVALID_OPERATION",
  STATE_CONFLICT: "STATE_CONFLICT",

  // System Errors (9xxx)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;
