import { Role } from "@prisma/client";
import { ROLES } from "./roles";
import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_DISABLE,
    PERMISSIONS.USER_ENABLE,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_UPDATE,
    PERMISSIONS.ITEM_DELETE,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.PROSPECT_CREATE,
    PERMISSIONS.PROSPECT_READ,
    PERMISSIONS.PROSPECT_UPDATE,
    PERMISSIONS.PROSPECT_DELETE,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_READ,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.QUOTATION_DELETE,
    PERMISSIONS.REPORTS_READ,
    // Scoped to the admin's own organization in auditService.getAuditLogs.
    PERMISSIONS.AUDIT_READ,
    // Authoring is forced to ORGANIZATION scope in announcementService; an admin
    // asking for a platform broadcast is rejected, not downgraded.
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_UPDATE,
    PERMISSIONS.ANNOUNCEMENT_DELETE,
    PERMISSIONS.ANNOUNCEMENT_PUBLISH,
    /**
     * Read-only on purpose. An admin sees their plan, renewal date and seat
     * usage but cannot change any of it — BILLING_MANAGE and PLAN_MANAGE are
     * super-admin only while billing is operated manually (decision D2).
     */
    PERMISSIONS.BILLING_READ,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_DISABLE,
    PERMISSIONS.USER_ENABLE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_UPDATE,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.PROSPECT_CREATE,
    PERMISSIONS.PROSPECT_READ,
    PERMISSIONS.PROSPECT_UPDATE,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_READ,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.REPORTS_READ,
  ],

  [ROLES.EXECUTIVE]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.PROSPECT_CREATE,
    PERMISSIONS.PROSPECT_READ,
    PERMISSIONS.PROSPECT_UPDATE,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_READ,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.REPORTS_READ,
  ],
};
