import type { StatusType } from "@/components/common/StatusBadge";
import type { AuditAction, AuditEntityType } from "@/contracts/types";

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  ORG_CREATED: "Organization Created",
  ORG_UPDATED: "Organization Updated",
  ORG_SUSPENDED: "Organization Suspended",
  ORG_ACTIVATED: "Organization Activated",
  ORG_ARCHIVED: "Organization Archived",
  ORG_RESTORED: "Organization Restored",
  USER_CREATED: "User Created",
  USER_UPDATED: "User Updated",
  USER_ROLE_CHANGED: "Role Changed",
  USER_DISABLED: "User Disabled",
  USER_ENABLED: "User Enabled",
  USER_DELETED: "User Deleted",
  USER_PASSWORD_RESET: "Password Reset",
  USER_PASSWORD_CHANGED: "Password Changed",
  USER_PROFILE_UPDATED: "Profile Updated",
  LEAD_CREATED: "Lead Created",
  LEAD_UPDATED: "Lead Updated",
  LEAD_DELETED: "Lead Deleted",
  LEAD_STATUS_CHANGED: "Lead Status Changed",
  LEAD_CONVERTED: "Lead Converted",
  PROSPECT_CREATED: "Prospect Created",
  PROSPECT_UPDATED: "Prospect Updated",
  ITEM_CREATED: "Item Created",
  ITEM_UPDATED: "Item Updated",
  ITEM_DELETED: "Item Deleted",
  QUOTATION_CREATED: "Quotation Created",
  QUOTATION_UPDATED: "Quotation Updated",
  QUOTATION_DELETED: "Quotation Deleted",
  QUOTATION_STATUS_CHANGED: "Quotation Status Changed",
  LOGIN_SUCCEEDED: "Login",
  LOGIN_FAILED: "Failed Login",
  SELF_SERVICE_SIGNUP: "Self-service Signup",
  ANNOUNCEMENT_CREATED: "Announcement Created",
  ANNOUNCEMENT_UPDATED: "Announcement Updated",
  ANNOUNCEMENT_PUBLISHED: "Announcement Published",
  ANNOUNCEMENT_ARCHIVED: "Announcement Archived",
  ANNOUNCEMENT_DELETED: "Announcement Deleted",
  PLAN_CREATED: "Plan Created",
  PLAN_UPDATED: "Plan Updated",
  SUBSCRIPTION_CREATED: "Subscription Created",
  SUBSCRIPTION_PLAN_CHANGED: "Plan Changed",
  SUBSCRIPTION_UPDATED: "Subscription Updated",
  SUBSCRIPTION_CANCELLED: "Subscription Cancelled",
};

export const AUDIT_ENTITY_LABELS: Record<AuditEntityType, string> = {
  ORGANIZATION: "Organization",
  USER: "User",
  AUTH: "Authentication",
  ANNOUNCEMENT: "Announcement",
  PLAN: "Plan",
  SUBSCRIPTION: "Subscription",
  LEAD: "Lead",
  PROSPECT: "Prospect",
  ITEM: "Item",
  QUOTATION: "Quotation",
};

/** Reuses StatusBadge's existing palette rather than introducing new colors. */
export const AUDIT_ACTION_BADGE_TYPE: Record<AuditAction, StatusType> = {
  ORG_CREATED: "success",
  ORG_UPDATED: "pending",
  ORG_SUSPENDED: "error",
  ORG_ACTIVATED: "success",
  ORG_ARCHIVED: "error",
  ORG_RESTORED: "success",
  USER_CREATED: "success",
  USER_UPDATED: "pending",
  USER_ROLE_CHANGED: "warning",
  USER_DISABLED: "error",
  USER_ENABLED: "success",
  USER_DELETED: "error",
  USER_PASSWORD_RESET: "warning",
  USER_PASSWORD_CHANGED: "warning",
  USER_PROFILE_UPDATED: "pending",
  LEAD_CREATED: "success",
  LEAD_UPDATED: "pending",
  LEAD_DELETED: "error",
  LEAD_STATUS_CHANGED: "warning",
  LEAD_CONVERTED: "success",
  PROSPECT_CREATED: "success",
  PROSPECT_UPDATED: "pending",
  ITEM_CREATED: "success",
  ITEM_UPDATED: "pending",
  ITEM_DELETED: "error",
  QUOTATION_CREATED: "success",
  QUOTATION_UPDATED: "pending",
  QUOTATION_DELETED: "error",
  QUOTATION_STATUS_CHANGED: "warning",
  LOGIN_SUCCEEDED: "inactive",
  LOGIN_FAILED: "error",
  SELF_SERVICE_SIGNUP: "success",
  ANNOUNCEMENT_CREATED: "success",
  ANNOUNCEMENT_UPDATED: "pending",
  ANNOUNCEMENT_PUBLISHED: "success",
  ANNOUNCEMENT_ARCHIVED: "warning",
  ANNOUNCEMENT_DELETED: "error",
  PLAN_CREATED: "success",
  PLAN_UPDATED: "pending",
  SUBSCRIPTION_CREATED: "success",
  SUBSCRIPTION_PLAN_CHANGED: "warning",
  SUBSCRIPTION_UPDATED: "pending",
  SUBSCRIPTION_CANCELLED: "error",
};

/** Field names shown in the before/after diff. */
export const AUDIT_FIELD_LABELS: Record<string, string> = {
  id: "ID",
  name: "Name",
  slug: "Slug",
  prefix: "Prefix",
  status: "Status",
  orgType: "Type",
  email: "Email",
  mobile: "Mobile",
  gstin: "GSTIN",
  address: "Address",
  authorizedPerson: "Authorized Person",
  firstName: "First Name",
  lastName: "Last Name",
  role: "Role",
  designation: "Designation",
  managerId: "Manager",
  organizationId: "Organization",
  reason: "Reason",
};
